
CREATE DATABASE PROYECTO;

CREATE TABLE REGISTRO(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(30) NOT NULL,
  CORREO VARCHAR(30) NOT NULL,
  CONTRASEÑA VARCHAR(50) NOT NULL
) CREATE TABLE FABRICANT ES(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  DIRECCION VARCHAR(50) NOT NULL,
  TELEFONO VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTOS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ID_FABRICANTE INT NOT NULL,
  ID_PRODUCTO INT NOT NULL,
  DESCRIPCION VARCHAR(15) NOT NULL,
  PRECIO FLOAT NOT NULL,
  EXISTENCIAS INT NOT NULL
);

CREATE TABLE PEDIDOS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NUMERO_PEDIDO INT NOT NULL,
  FECHA_PEDIDO DATE NOT NULL,
  ID_CLIENTE INT NOT NULL,
  ID_EMPLEADO INT NOT NULL,
  ID_FABRICANTE VARCHAR(7) NOT NULL,
  PRODUCTO VARCHAR(10) NOT NULL,
  CANTIDAD INT NOT NULL,
  IMPORTE FLOAT NOT NULL
);

CREATE TABLE OFICINAS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  OFICINA INT NOT NULL,
  CIUDAD VARCHAR(30) NOT NULL,
  REGION VARCHAR(20) NOT NULL,
  DIRECCION VARCHAR(50),
  OBJETIVO FLOAT,
  VENTAS FLOAT
);

CREATE TABLE ESTUDIANTES(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  MATRICULA INT,
  NOMBRE VARCHAR(50) NOT NULL,
  DIRECCION VARCHAR(45) NOT NULL,
  NUMERO INT NOT NULL,
  CARRERA VARCHAR(45) NOT NULL
);

CREATE TABLE MATERIAS(
  NUM_MATERIA INT PRIMARY KEY AUTO_INCREMENT,
  MATERIA VARCHAR(50) NOT NULL
);

ALTER TABLE MATERIAS ADD CONSTRAINT MATERIAS_FK1 FOREIGN KEY (MATRICULA) REFERENCES ESTUDIANTES(MATRICULA) ON DELETE CASCADE ON UPDATE CASCADE;

-- normalizacion
CREATE TABLE CLIENTES (
  ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDO VARCHAR(50),
  CEDULA VARCHAR(50),
  CORREO VARCHAR(50)
);

CREATE TABLE HABITACIONES (
  ID_HABITACION INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DISPONIBILIDAD VARCHAR(50) NOT NULL
);

CREATE TABLE RESERVAS (
  ID_RESERVA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FECHA VARCHAR(50) NOT NULL,
  VIGENCIA VARCHAR(50) NOT NULL
);

CREATE TABLE SEDE (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  DIRECCION VARCHAR(50),
  CODIGO VARCHAR(50)
);

CREATE TABLE CARRERA (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  CODIGO VARCHAR(50) NOT NULL
);

CREATE TABLE ALUMNO_CURSO (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_CURSO INT NOT NULL,
  ID_ALUMNO INT NOT NULL
);

CREATE TABLE DOCENTE_CURSO (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_DOCENTE INT NOT NULL,
  ID_CURSO INT NOT NULL
);

CREATE TABLE CURSO_CARRERA (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_CURSO INT NOT NULL,
  ID_CARRERA INT NOT NULL
);

CREATE TABLE SEDE_CARRERA (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_SEDE INT NOT NULL,
  ID_CARRERA INT NOT NULL
);

ALTER TABLE ALUMNO_CURSO ADD CONSTRAINT ALUMNO_CURSOFK1 FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNO(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ALUMNO_CURSO ADD CONSTRAINT ALUMNO_CURSOFK2 FOREIGN KEY(ID_CURSO) REFERENCES CURSO(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DOCENTE_CURSO ADD CONSTRAINT DOCENTE_CURSOFK1 FOREIGN KEY(ID_DOCENTE) REFERENCES DOCENTE(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE DOCENTE_CURSO ADD CONSTRAINT DOCENTE_CURSOFK2 FOREIGN KEY(ID_CURSO) REFERENCES CURSO(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CURSO_CARRERA ADD CONSTRAINT CURSO_CARRERAFK1 FOREIGN KEY(ID_CURSO) REFERENCES CURSO(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CURSO_CARRERA ADD CONSTRAINT CURSO_CARRERAFK2 FOREIGN KEY(ID_CARRERA) REFERENCES CARRERA(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SEDE_CARRERA ADD CONSTRAINT SEDE_CARRERAFK1 FOREIGN KEY(ID_SEDE) REFERENCES SEDE(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SEDE_CARRERA ADD CONSTRAINT SEDE_CARRERAFK2 FOREIGN KEY(ID_CARRERA) REFERENCES CARRERA(ID) ON UPDATE CASCADE ON DELETE CASCADE;