-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 14:33:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `ID_Cliente` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(40) NULL,
  `Apellido` VARCHAR(40) NULL,
  `Correo` VARCHAR(100) NULL,
  `Teléfono` CHAR(11) NULL,
  PRIMARY KEY (`ID_Cliente`));


-- -----------------------------------------------------
-- Table `mydb`.`Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Compras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Compras` (
  `Id_Compra` INT NOT NULL AUTO_INCREMENT,
  `Proovedores_Nit` INT UNSIGNED NOT NULL,
  `Productos_ID_Producto` INT NOT NULL,
  `Fecha` DATE NULL,
  `Cantidad` VARCHAR(45) NULL,
  `Med_pago` VARCHAR(45) NULL,
  `Precio_Tot` MEDIUMINT NULL,
  `Num_Factura` VARCHAR(15) NULL,
  `Clientes_ID_Cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id_Compra`));


-- -----------------------------------------------------
-- Table `mydb`.`Detalles_de_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Detalles_de_ventas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Detalles_de_ventas` (
  `ID_Detalles` INT NOT NULL,
  `Cantidad` VARCHAR(45) NULL,
  `Precio_Unitario` VARCHAR(45) NULL,
  `Descuento` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Detalles`));


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `ID_Usuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Usuarios`));


-- -----------------------------------------------------
-- Table `mydb`.`Existencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Existencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Existencias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` SMALLINT UNSIGNED NOT NULL,
  `Precio` SMALLINT UNSIGNED NULL,
  `Productos_ID_Producto` INT NOT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `ID_Producto` INT NOT NULL,
  `Nombre_Producto` VARCHAR(50) NOT NULL,
  `Descripción_Producto` VARCHAR(100) NULL,
  `Categoria` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_Producto`));


-- -----------------------------------------------------
-- Table `mydb`.`Proovedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proovedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proovedores` (
  `Nit` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`Nit`));


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Rol` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`));


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `ID_Venta` INT NOT NULL,
  `Fecha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_Venta`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
